### ISSUE TITLE
No movies found on mac os

### ISSUE THREAD

**Issue by sytolk** [lacymorrow/cinematic#51]
## Current Behavior
![6D474F6A-1AED-4015-B1E7-2A511FEB4528](https://github.com/lacymorrow/cinematic/assets/1415463/7fafe158-f34e-466e-a732-aaca80badd7e)

**Comment by sytolk** [comment]
maybe the problem is with you listDirectory impl this function is used from TagSpaces: https://github.com/tagspaces/tagspaces-common/blob/develop/packages/common/io-fsclient.js#L448

**Comment by lacymorrow** [comment]
Heyo! Thanks for checking out this project!

There have actually been 3 iterations of Cinematic, one built with Meteor, one with Nextron, and the most recent release with React (and Electron).

The screenshot you shared is from v1, I'm surprised it even opened for you! It's rare that I have someone willing to test the bleeding-edge versions of projects, I'll try to post an updated build now, would you be interested in taking it for a test run later today?

**Comment by sytolk** [comment]
Hello I suppose that today is tonight for me but we are working for the same kind of projets (file managers based on electron-react-boilerplate) and.. why not ? I can give you free feedback too ;) I'll be waiting for the new package

**Comment by sytolk** [comment]
Electron app gennerally works but it's look like work in progress it's have duplicate files on Add Media twice. Thumbnails is missing. it's not the same screen like in readme:
![A1EFE46A-5170-431D-98A7-1F95A3750562](https://github.com/lacymorrow/cinematic/assets/1415463/1005fe22-b54e-4d0e-8d67-70f375f4df2c)
You can use free version of [TagSpaces](https://github.com/tagspaces/tagspaces/releases/tag/v5.6.2) for watching movies (with HTML5 player) now cinematic open VLC the third party player - what happened if I don't have player installed. What is you idea behind cinematic app? I don't know what make cinematic app unique?

**Comment by lacymorrow** [comment]
Oh wow, you went ahead and ran it locally! I was trying to tie up loose ends and build an executable for you.

I appreciate you taking a look, at this point it's is still a work in progress, could you potentially provide the filenames of the three files you used? It's not properly parsing the titles correctly so it's unable to find information.

TagSpaces is fantastic! Very well put together and I appreciate the polish. I'd love to know how you managed to get packaging for Android working (looks like Cordova).

Honestly the intention of Cinematic is more or less useless and better handled by plex and jellyfin. 

**Essentially**: I have a giant library of movies and I'm not sure what to watch. I load the directory in Cinematic to give me more information than just filenames (trailers, photos, actors, etc.) and I can open the file on my local machine.

It's lighter than running a Plex instance but it's definitely a product for a demographic of no one :)

**Comment by Eccomi21** [comment]
> It's lighter than running a Plex instance but it's definitely a product for a demographic of no one :)

I am no one then :D maybe I am missing something, but I came to the issue here because I decided to try out cinematic for myself. After gathering a decent amount of `Movies.That.Look.Like.This.2015.HDRip.XviD.XXX-XXX.AVI` I thought it might be a great tool to organize them. Yet it doesn't seem to handle any of them.
First I thought that is because the folder I pointed to has subfolders with the actual file inside of it, so I pointed it to the folder containing the movie itself, and renamed the movie to a better readable format. Unfortunately, that did not work either.
I am on Windows though, not MacOS.

Unfortunately, since I am no programmer outside of Hello world, I can't look into it myself really :(

**Comment by sytolk** [comment]
@lacymorrow My files is not 3 it is 2 located in subfolders of /Downloads: 
file1 path (The duplicate file): `/Users/sytolk/Downloads/Grease.1978.1080p.BluRay.x265.DD5.1-WAR/Grease.1978.1080p.BluRay.x265.DD5.1-WAR.mkv`
file2 path: `/Users/sytolk/Downloads/Lyle.Lyle.Crocodile.2022.BDRip.x264.AAC.BGAUDiO-SiSO/Lyle.Lyle.Crocodile.2022.BDRip.x264.AAC.BGAUDiO-SiSO.mkv`

How to repeat duplicate file issue:
1. Click on "Add media" and choose "Downloads" folder -it will add 2 files
2. Click on "Add media" again and choose "Downloads" folder - it will duplicate file1 only = 3 files

It's strange here why file2 is not duplicated??

For cordova tagspaces uses [tagspaces-common](https://github.com/tagspaces/tagspaces-common/tree/develop) this [library](https://www.npmjs.com/package/@tagspaces/tagspaces-common-cordova) is like common interface for IO oprations in all [platforms](https://www.npmjs.com/package/@tagspaces/tagspaces-platforms). It's have MIT license you can fork and use it as you wish.

**Comment by sytolk** [comment]
Guys I'm 45 years old. Maybe you are the next generation that is trying to do the same thing ? :) Yes maybe Plex is better but I can't find Plex [source code](https://www.reddit.com/r/PleX/comments/cxa3ex/is_there_a_way_to_take_plexs_source_code_and_make/?rdt=42580) and [jellyfin](https://github.com/jellyfin/jellyfin) C# MS devs.. not for me. I'm not so exited from the functionallity and design of the application. For me is more important the software architecture and the quality of the source code. That's the reason to join to the TagSpaces. It's not only file manager with search it support integrations with third party extensions. This is the extension for watching movies: https://github.com/tagspaces/tagspaces-extensions/tree/main/media-player I have personal extension for tagspaces that can be installed from settings: https://github.com/sytolk/mental-arithmetic (Readme is missing I know..)
I want to say that I appreciate your effort but I think it's better to not loose the time diff (45-x) to write source code from the scratch and the results of your work to be seen by yourself not only by future generations ;)

**Comment by lacymorrow** [comment]
@Eccomi21 @sytolk It is basically an issue with how I am parsing file names/years. For the last 20 years or so I've kept movies organized in a `[title] - [year]` format. The application itself won't show any data if it cannot find anything on TMDB/OMDB/IMDB.
Basically, "garbage in, garbage out". 

You can create files like 
<img width="256" alt="image" src="https://github.com/lacymorrow/cinematic/assets/1311301/c228383b-e070-4917-a9df-348004a964b3">

To get something like 
<img width="1152" alt="image" src="https://github.com/lacymorrow/cinematic/assets/1311301/8fdbada4-e9cb-4e17-8bff-73ba0bec2c21">

I'll work on the parsing of torrent names

**Comment by lacymorrow** [comment]
I've fixed it, this project is still a work-in-progress however

**Comment by lacymorrow** [comment]
Stable https://github.com/lacymorrow/cinematic/releases
