### ISSUE TITLE
Select Color not Working

### ISSUE THREAD

**Issue by Alyakar** [lacymorrow/cinematic#73]
Hello, I was testing Cinematic 3.0.0 under Windows 11 and in Settings -> Appearance -> Accent Color there is an option to Select Color, you can click it and a control to select the color appears, but it doesn't move at all, also it's impossible to change the color with RGB or HEX options. Not sure if it's just me or there is something wrong with that option. I've tried both, dark and light modes, but it doesn't work with any of them.

I know this is not very important, but just wanted to make you know it.

Greetings!

**Comment by lacymorrow** [comment]
Thank you!

I wouldn't have found it myself.

**Comment by lacymorrow** [comment]
Fixed https://github.com/lacymorrow/cinematic/releases

**Comment by lacymorrow** [comment]
Stable version https://github.com/lacymorrow/cinematic/releases
